### ISSUE TITLE
老哥是怎么更换的BCM94360CS2网卡的？

### ISSUE THREAD

**Issue by fengcms** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#1]
我从网上买了一块网卡，拆解后发现接口不对，主板自带的是m.2接口的无线网卡插槽，而我购买的是 mini-PCI-E 插槽的 -_-|||。
想问老哥是购买的m.2插槽的无线网卡，然后将主板自带的无线网卡给替换下来的吗？
如果是这样操作的话，天线的连接麻烦吗？需要用到洛铁吗？

**Comment by WenvyG** [comment]
你直接上淘宝再买一个苹果原装网卡转NGFF M.2/E Key的转接板，就十几块。最后成品是这样子的https://img.alicdn.com/imgextra/i1/52923029/O1CN01SqS0kK1YFKFmwgajD_!!52923029.jpg
然后把主板上的原装拆了换掉就可以了。原来的网卡屏蔽罩可能只能装一半。
天线是直接扣的，不用烙铁。

**Comment by fengcms** [comment]
@WenvyG 你的意思是，买一个转接板，就可以将 mini-pci-e 的无线网卡给插到转接板上，然后再插到主板上就好了是吗？

**Comment by fengcms** [comment]
@WenvyG 已经买了并安装上了。现在是无线网卡正常，蓝牙不识别。使用了 BrcmPatchRAM 的三个 kext 后，蓝牙芯片是识别了，但是找不到任何设备-_-|||

**Comment by fengcms** [comment]
不好意思，找不到设备是天线没接好，刚想起来接了天线就好了。。。。
