### ISSUE TITLE
请教：OC0.6.5引导安装bigsur出现准备更新时出错

### ISSUE THREAD

**Issue by jiangchn1990** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#11]
感谢老哥分享，请教一个问题：

OC0.6.5引导安装bigsur，在两次进度条走完后，出现macos更新助理/准备更新时出错 这个错误 不知道是哪里出问题了？

机器配置：
主板：华擎 Z370 pro4
显卡：蓝宝石 Rx590
内存：阿斯加特 2666 32g*2
SSD：海康威视C2000 pro *2
硬盘：西数蓝盘1T

双盘双系统（windows已安装）

![微信图片_20210122102414](https://user-images.githubusercontent.com/32585903/105437456-14e2e600-5c9c-11eb-8b14-aaa591157130.jpg)

**Comment by WenvyG** [comment]
我也不知道具体情况。
你要不用11.1的安装包重新做一遍安装盘，然后试试重新安装一下
