### ISSUE TITLE
感谢大佬提供的efi，我有几个问题想请教一下大佬

### ISSUE THREAD

**Issue by seepine** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#12]
我的配置如下
类型 |  型号         
---|---
主板 | 华擎b460m-itx 
cpu  | i5 10400    
内存 | 十铨16g*2 3200灯条 
散热 | 利民axp90i    
电源 | 益衡7660B flex 小1U
硬盘 | 海康威视c2000pro 1TB

1. 请问这个配置是否能使用你的efi呢
2. 如果可以的话，我看readme提到三码要生成，是否使用GenSMBIOS这个生成吗
3. 我还没有更换网卡，但是我之前笔记本上有一个DW1820A，能否直接使用呢，还是需要BCM94360CS2呢

**Comment by WenvyG** [comment]
> 我的配置如下
> 
> 类型	型号
> 主板	华擎b460m-itx
> cpu	i5 10400
> 内存	十铨16g*2 3200灯条
> 散热	利民axp90i
> 电源	益衡7660B flex 小1U
> 硬盘	海康威视c2000pro 1TB
> 1. 请问这个配置是否能使用你的efi呢
> 2. 如果可以的话，我看readme提到三码要生成，是否使用GenSMBIOS这个生成吗
> 3. 我还没有更换网卡，但是我之前笔记本上有一个DW1820A，能否直接使用呢，还是需要BCM94360CS2呢

1.你的华擎B460M-ITX和B460M-ITX/ac相比，板载声卡和有线网卡不同，另外好像也没有插无线网卡的NGFF接口。不过你可以按我说的设置一下BIOS，然后尝试安装一下，大概率可以。声卡的话需要改alcid，网卡用螃蟹千兆网卡的kext。

2.生成三码的方法很多，GenSMBIOS就可以。另外OCC，Hackintool也可以。

3.网卡不需要一定是BCM94360CS2，其他的可以驱动的无线网卡也可以。DW1820A我没有这张卡，具体情况建议你看看黑果小兵的文章：[《DW1820A/BCM94350ZAE/BCM94356ZEPA50DX插入的正确姿势 》](https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)。

**Comment by seepine** [comment]
哦哦是我说错了，我也是B460M-ITX/ac，那就说明efi全部都不需要改了是吧

网卡的话安装系统会不会有影响（比如我是原装网卡，先安装系统使用网线联网，后续再更换免驱网卡），这样是否可行呢

**Comment by WenvyG** [comment]
> 哦哦是我说错了，我也是B460M-ITX/ac，那就说明efi全部都不需要改了是吧
> 
> 网卡的话安装系统会不会有影响（比如我是原装网卡，先安装系统使用网线联网，后续再更换免驱网卡），这样是否可行呢

安装完后再换免驱卡是可以的。

**Comment by seepine** [comment]
感谢大佬我成功装上并可以使用了，目前除了wifi（没有更换网卡），其他基本正常，目前遇到两个问题需请教一下大佬
1. 我efi是放在u盘的启动的，现在装好了系统后，如何操作才能脱离u盘，使用硬盘启动呢（我固态已经分了300MB的esp分区）
2. 休眠后显示器黑屏，我无法通过键盘或鼠标来唤醒屏幕，需要拔掉hdmi重新插上，请问这个该如何解决呢

**Comment by WenvyG** [comment]
试试在Hackintool--电源里，点下面的那个螺丝刀图案，修复一下电源设置，另外只有核显要用EFI-iGPU。

**Comment by seepine** [comment]
config-dGPU.plist
config.plist

我下载下来的efi有这两个，我没有变动，那应该使用的就是iGPU了吧，修复电源的话我明天试一下

**Comment by WenvyG** [comment]
> config-dGPU.plist
> config.plist
> 
> 我下载下来的efi有这两个，我没有变动，那应该使用的就是iGPU了吧，修复电源的话我明天试一下

用release里的，[EFI-iGPU](https://github.com/WenvyG/ASRock-B460M-ITX-ac-Hackintosh/releases/download/4.0/EFI-iGPU.zip)

**Comment by seepine** [comment]
我用release的EFI-iGPU，然后点了修复电源，还是一样无法唤醒...

是否会和bios版本有关呢，或者bios的`CSM`配置有关？因安装前准备步骤我就差这一步
>开机按F2或Del进入BIOS
Disabled:
  Secure Boot
  CSM
  CFGLock
  VT-d
Enable:
XHCI Hand Off
Above 4GB Decoding

其中的CSM我没有设置，因为我没有找到它在什么地方...

**Comment by seepine** [comment]
大佬会不会是usb的问题呢，我百度有看到类似的说要定制usb什么的

**Comment by seepine** [comment]
大佬今天遇到了个状态，原装的网卡今天蓝牙突然用着用着也失灵了（连接airport+蓝牙键盘）
也不晓得什么原因，干脆一次搞定换个网卡，所以想请教一下，网卡是直接购买BCM94360CS2就可以吗
1. 其中有2天线和3天线的，是购买2天线的吗（主板后面好像就两个天线）
2. 另外是拆掉主板现在的网卡，直接把买来的BCM94360CS2换上去就可以吗，还是说还要买什么NGFF转接卡？

**Comment by WenvyG** [comment]
> 大佬今天遇到了个状态，原装的网卡今天蓝牙突然用着用着也失灵了（连接airport+蓝牙键盘）
> 也不晓得什么原因，干脆一次搞定换个网卡，所以想请教一下，网卡是直接购买BCM94360CS2就可以吗
> 
> 1. 其中有2天线和3天线的，是购买2天线的吗（主板后面好像就两个天线）
> 2. 另外是拆掉主板现在的网卡，直接把买来的BCM94360CS2换上去就可以吗，还是说还要买什么NGFF转接卡？

两天线的就可以
需要转接卡，原装网卡的屏蔽壳会装不上
