### ISSUE TITLE
BCM94360CS2 & Airpods 问题

### ISSUE THREAD

**Issue by bwelco** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#3]
问题描述：
https://github.com/ansonliao/Asrock-B460m-ITX-AC-OC-EFI/issues/3

**Comment by WenvyG** [comment]
我并没有遇到这样的问题。我的AirPods连Hackintosh的时候和和连iPhone和MacBook的时候感觉没差。
不过你可以试试https://github.com/acidanthera/AirportBrcmFixup，**可能有用**，具体使用方法你自己看看

**Comment by bwelco** [comment]
试了，好像不太行，请问可以帮忙看下你的 airpods 连上黑苹果之后，Audio MIDI setup 里面的 airpods mic 频率吗？
