### ISSUE TITLE
XHCI-unsupported.kext 和 HibernationFixup.kext 是必须的吗？

### ISSUE THREAD

**Issue by chenfeicqq** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#4]
非常感谢老哥的分享，给我带来不少帮助，有几个疑问向您请教下

1. XHCI-unsupported.kext 和 HibernationFixup.kext 是必须的吗？分别的用途是什么？或者删掉会有什么问题？
2. OpenCanopy.efi 使用效果是什么样的？我看放了图片和字体资源；感觉是用于 多系统启动选择的，但是 win10 不是通过 Boot Camp 安装启动的吗？

**Comment by WenvyG** [comment]
1.前者必须有，这是关于USB控制器的；后者可以删除，我发布在release的包里就没有HibernationFixup.kext。
2.OpenCanopy.efi 是让OpenCore在选择启动磁盘有图形化界面的。虽然Windows 10 和macOS 是可以通过Boot Camp进行相互启动转换的，但我还是更习惯在开机时保留2s的可以选择启动磁盘的时间（clover遗留习惯）。你也可以设置倒计时为0，让OpenCore直接引导默认系统，然后直接用Boot Camp 切换以及Cmd + R 进入Recovery模式等操作。

**Comment by chenfeicqq** [comment]
感谢回复，查了资料，OpenCanopy 已经搞明白了。

XHCI-unsupported 我看官方资料上提示 B460 主板可以不用，不是能明白这个的作用
https://dortania.github.io/OpenCore-Install-Guide/ktext.html#usb
![image](https://user-images.githubusercontent.com/2122266/98457083-0584ee00-21bf-11eb-9596-46f8a9c9e179.png)

**Comment by chenfeicqq** [comment]
AsRock boards(On Intel motherboards specifically, B460/Z490+ boards do not need it however)

**Comment by chenfeicqq** [comment]
还有一个问题

Hackintool 中除了 usb 显示 ？？ 外，还有2个地方也是 ？？ 不知道老哥你遇到过没有？

系统-序列号信息-型号
系统-序列号信息-型号标识符

音频-声音信息-设备
音频-声音信息-子设备

**Comment by WenvyG** [comment]
# 首先第一个问题
`我看过很多遍你说的Dortania的教程`，所以我可以告诉你**这个教程并不一定全部准确**，而且这个教程有些部分更新并不及时，不需要全相信教程所说，自己试过才知道怎么样才合适。我也确实试过不加XHCI-unsupported.kext，那么内置的USB设备和外置的USB设备就不能被自动正确识别；换做USBInjectall.kext之后，USB定制后得到的USBPort.kext就没用了。
# 第二个问题
系统-序列号信息-型号、系统-序列号信息-型号标识符；音频-声音信息-设备、音频-声音信息-子设备之中的`???`，因为我看着不影响正常使用所以就没研究是什么原因。
后者应该可以通过在`DeviceProperties`中复制声卡PCI地址并添加相关属性来解决。**前者如果你有解决方法的的话也感谢你来告知我如何解决**😊😊😊。

**Comment by chenfeicqq** [comment]
感谢，确实被文档坑了，试了下 XHCI 不加的话，USB3.0 的设备识别不了。

设备？？的问题我再研究研究。

**Comment by chenfeicqq** [comment]
试了下你的 usb 定制，好像定制后的数量是 16 个。
网上查阅的资料好像不能超过 15 个？不确定谁是对的？

**Comment by chenfeicqq** [comment]
usb 设备问号的问题可能是 USBInjectall.kext 未适配最新的主板芯片组 以及 mac 设备信息。

发现一位前辈的 fork 对 B460 以及 iMac20,1 做了适配，用这个应该能解决问题，晚上回去试下。

https://github.com/daliansky/OS-X-USB-Inject-All

**Comment by chenfeicqq** [comment]
试了，没用...
