### ISSUE TITLE
接力可以正常使用吗？

### ISSUE THREAD

**Issue by chenfeicqq** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#6]
3台设备：
1. macbook 白苹果；
2. iphone；
3. 黑苹果；

隔空投送功能一切正常，但是接力有问题，iphone 和 白苹果 上 复制文本 或 文件，可以在黑苹果上正常粘贴；

但是黑苹果上 复制文本 或 文件，在白苹果 或 iphone 上无法粘贴；

**Comment by WenvyG** [comment]
想想是不是你硬件的问题

**Comment by chenfeicqq** [comment]
硬件配置除了 cpu 是 10400 其他和你是一样的，网卡是 BCM94360CS2。

**Comment by chenfeicqq** [comment]
你是正常的吗？

**Comment by WenvyG** [comment]
正常，iPhone、MacBook和台式都没问题
