### ISSUE TITLE
主板传感器是否正常使用？

### ISSUE THREAD

**Issue by chaosk731** [WenvyG/ASRock-B460M-ITX-ac-Hackintosh#9]
Q1:b460m-itx-ac的主板传感器可正常显示吗？
Q2:风扇的转速可显示？
想通过istat查看温度以及对cpu风扇进行调速

**Comment by WenvyG** [comment]
可以看到CPU温度，但不能看到风扇转速

**Comment by chaosk731** [comment]
> 可以看到CPU温度，但不能看到风扇转速

有什么办法解决风扇调速吗？（软件手段）

**Comment by WenvyG** [comment]
> > 可以看到CPU温度，但不能看到风扇转速
> 
> 有什么办法解决风扇调速吗？（软件手段）

暂时应该是无解
